<#
.SYNOPSIS
    A Network Troubleshooting Command Palette.
.DESCRIPTION
    This script provides a menu-driven interface for common network troubleshooting tasks.
    It includes connectivity tests, DNS lookups, port checks, and local adapter information.
.AUTHOR
    Generated by Antigravity
.DATE
    2026-02-13
#>

function Show-Menu {
    Clear-Host
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host "   Network Troubleshooting Palette      " -ForegroundColor White
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host "1. Test Connectivity (Ping)"
    Write-Host "2. Trace Route (Tracert)"
    Write-Host "3. DNS Lookup (Resolve-DnsName)"
    Write-Host "4. Test Port (Test-NetConnection)"
    Write-Host "5. Show Application Connections (Get-NetTCPConnection)"
    Write-Host "6. Show Local Adapter Info"
    Write-Host "7. Show Routing Table"
    Write-Host "8. Check Public IP"
    Write-Host "9. Check Wi-Fi Signal"
    Write-Host "10. Check SSL Certificate"
    Write-Host "11. Check Interface MTU"
    Write-Host "12. Port Scanner (Common Ports)"
    if ($script:LoggingEnabled) {
        Write-Host "L. Stop Logging (Transcript Active)" -ForegroundColor Green
    }
    else {
        Write-Host "L. Start Logging"
    }
    Write-Host "Q. Quit"
    Write-Host "========================================" -ForegroundColor Cyan
}

function Test-Connectivity {
    param()
    Write-Host "`n--- Test Connectivity (Ping) ---" -ForegroundColor Yellow
    $target = Read-Host "Enter Hostname or IP"
    if ([string]::IsNullOrWhiteSpace($target)) { return }
    
    try {
        Test-Connection -ComputerName $target -Count 4 -ErrorAction Stop | Format-Table -AutoSize
    }
    catch {
        Write-Error "Failed to ping $target. Error: $_"
    }
    Pause
}

function Trace-Route {
    param()
    Write-Host "`n--- Trace Route ---" -ForegroundColor Yellow
    $target = Read-Host "Enter Hostname or IP"
    if ([string]::IsNullOrWhiteSpace($target)) { return }

    # Using cmd tracert for better output visualization than strict powershell sometimes, 
    # but Test-NetConnection -TraceRoute is also an option. Sticking to standard tracert for familiarity.
    tracert $target
    Pause
}

function DNS-Lookup {
    param()
    Write-Host "`n--- DNS Lookup ---" -ForegroundColor Yellow
    $target = Read-Host "Enter Hostname or IP"
    if ([string]::IsNullOrWhiteSpace($target)) { return }

    try {
        Resolve-DnsName -Name $target -ErrorAction Stop | Format-Table -AutoSize
    }
    catch {
        Write-Error "DNS Resolution failed for $target. Error: $_"
    }
    Pause
}

function Test-Port {
    param()
    Write-Host "`n--- Test Port ---" -ForegroundColor Yellow
    $target = Read-Host "Enter Hostname or IP"
    if ([string]::IsNullOrWhiteSpace($target)) { return }
    $port = Read-Host "Enter Port Number (e.g., 80, 443, 3389)"
    
    if (-not [int]::TryParse($port, [ref]$null)) {
        Write-Warning "Invalid port number."
        Pause
        return
    }

    try {
        Test-NetConnection -ComputerName $target -Port $port | Select-Object ComputerName, RemoteAddress, RemotePort, TcpTestSucceeded, SourceAddress
    }
    catch {
        Write-Error "Port test failed. Error: $_"
    }
    Pause
}

function Show-Connections {
    Write-Host "`n--- Active TCP Connections (Top 20) ---" -ForegroundColor Yellow
    Get-NetTCPConnection | Sort-Object State, LocalPort | Select-Object -First 20 | Format-Table -AutoSize
    Write-Host "Note: Listing limited to top 20 for readability." -ForegroundColor Gray
    Pause
}

function Show-AdapterInfo {
    Write-Host "`n--- Local Adapter Information ---" -ForegroundColor Yellow
    Get-NetAdapter | Where-Object Status -eq 'Up' | Format-Table -AutoSize
    
    Write-Host "`n--- IP Configuration ---" -ForegroundColor Yellow
    Get-NetIPConfiguration | Format-List InterfaceAlias, IPv4Address, IPv6Address, DNSServer
    Pause
}

function Show-Routing {
    Write-Host "`n--- IP Routing Table ---" -ForegroundColor Yellow
    Get-NetRoute | Sort-Object DestinationPrefix | Format-Table -Property DestinationPrefix, NextHop, RouteMetric, InterfaceAlias -AutoSize
    Pause
}

function Get-PublicIP {
    Write-Host "`n--- Public IP Address ---" -ForegroundColor Yellow
    try {
        $ipInfo = Invoke-RestMethod -Uri "https://ipinfo.io/json" -ErrorAction Stop
        Write-Host "Public IP: $($ipInfo.ip)" -ForegroundColor Green
        Write-Host "City:      $($ipInfo.city)"
        Write-Host "Region:    $($ipInfo.region)"
        Write-Host "Country:   $($ipInfo.country)"
        Write-Host "Org:       $($ipInfo.org)"
    }
    catch {
        Write-Error "Failed to retrieve Public IP. Check internet connectivity. Error: $_"
    }
    Pause
}

function Get-WifiSignal {
    Write-Host "`n--- Wi-Fi Signal Strength ---" -ForegroundColor Yellow
    $wifiStatus = netsh wlan show interfaces
    if ($wifiStatus) {
        $wifiStatus | Select-String "SSID", "Signal", "Radio type", "Band", "Channel", "Receive rate", "Transmit rate" | ForEach-Object { Write-Host $_.Line.Trim() }
    }
    else {
        Write-Warning "No Wi-Fi interface found or Wireless AutoConfig service is not running."
    }
    Pause
}

function Test-SSL {
    param()
    Write-Host "`n--- SSL Certificate Check ---" -ForegroundColor Yellow
    $target = Read-Host "Enter Domain Name (e.g. google.com)"
    if ([string]::IsNullOrWhiteSpace($target)) { return }
    $port = 443

    try {
        $tcpClient = New-Object Net.Sockets.TcpClient($target, $port)
        $sslStream = New-Object Net.Security.SslStream($tcpClient.GetStream(), $false, ({ $true } -as [Net.Security.RemoteCertificateValidationCallback]))
        $sslStream.AuthenticateAsClient($target)
        $cert = $sslStream.RemoteCertificate
        
        $cert2 = [System.Security.Cryptography.X509Certificates.X509Certificate2]$cert
        
        Write-Host "Subject:    $($cert2.Subject)"
        Write-Host "Issuer:     $($cert2.Issuer)"
        Write-Host "Effective:  $($cert2.NotBefore)"
        Write-Host "Expires:    $($cert2.NotAfter)" -ForegroundColor $(if ($cert2.NotAfter -lt (Get-Date).AddDays(30)) { "Red" } else { "Green" })
        Write-Host "Days Left:  $([math]::Round(($cert2.NotAfter - (Get-Date)).TotalDays))"
        
        $tcpClient.Close()
    }
    catch {
        Write-Error "Failed to retrieve SSL certificate for $target. Error: $_"
    }
    Pause
}

function Get-MTU {
    Write-Host "`n--- Interface MTU Sizes ---" -ForegroundColor Yellow
    Get-NetIPInterface | Where-Object ConnectionState -eq 'Connected' | Sort-Object NlMtu -Descending | Select-Object IfIndex, InterfaceAlias, AddressFamily, NlMtu | Format-Table -AutoSize
    Pause
}

function Invoke-PortScan {
    param()
    Write-Host "`n--- Port Scanner (Common Ports) ---" -ForegroundColor Yellow
    $target = Read-Host "Enter Hostname or IP"
    if ([string]::IsNullOrWhiteSpace($target)) { return }
    
    $commonPorts = @(21, 22, 23, 25, 53, 80, 110, 135, 139, 143, 443, 445, 3389, 8080)
    
    Write-Host "Scanning $target for common ports..."
    
    foreach ($port in $commonPorts) {
        $status = Test-NetConnection -ComputerName $target -Port $port -WarningAction SilentlyContinue
        if ($status.TcpTestSucceeded) {
            Write-Host "Port $port : OPEN" -ForegroundColor Green
        }
    }
    Write-Host "Scan complete."
    Pause
}

function Toggle-Logging {
    $date = Get-Date -Format "yyyyMMdd-HHmm"
    $logPath = "$PSScriptRoot\NetworkLog-$date.txt"
    
    if ($script:LoggingEnabled) {
        Stop-Transcript
        $script:LoggingEnabled = $false
        Write-Host "Logging stopped." -ForegroundColor Green
        Pause
    }
    else {
        try {
            Start-Transcript -Path $logPath -Append
            $script:LoggingEnabled = $true
            Write-Host "Logging started to $logPath" -ForegroundColor Green
            Pause
        }
        catch {
            Write-Error "Failed to start transcript: $_"
            Pause
        }
    }
}

# Main Loop
$script:LoggingEnabled = $false

do {
    Show-Menu
    $selection = Read-Host "Select an option"
    
    switch ($selection) {
        '1' { Test-Connectivity }
        '2' { Trace-Route }
        '3' { DNS-Lookup }
        '4' { Test-Port }
        '5' { Show-Connections }
        '6' { Show-AdapterInfo }
        '7' { Show-Routing }
        '8' { Get-PublicIP }
        '9' { Get-WifiSignal }
        '10' { Test-SSL }
        '11' { Get-MTU }
        '12' { Invoke-PortScan }
        'L' { Toggle-Logging }
        'l' { Toggle-Logging }
        'Q' { 
            if ($script:LoggingEnabled) { Stop-Transcript }
            Write-Host "Exiting..."
            return
        }
        'q' { 
            if ($script:LoggingEnabled) { Stop-Transcript }
            Write-Host "Exiting..."
            return
        }
        default { 
            Write-Warning "Invalid selection. Please try again." 
            Start-Sleep -Seconds 1
        }
    }
} while ($true)
