<#
.SYNOPSIS
    Fixes cursor visibility issues in Windows applications by enabling Overlay Test Mode for the Desktop Window Manager (DWM).

.DESCRIPTION
    This script modifies the Windows Registry to set OverlayTestMode to 5, which can help resolve cursor problems
    where the mouse pointer appears behind overlaid windows in certain applications or environments.

.PARAMETER None
    This script takes no parameters.

.EXAMPLE
    .\CursorFix.ps1

.NOTES
    - Requires administrator privileges to modify HKLM registry.
    - This is a common fix for cursor issues in Citrix, RDS, or other virtualized environments.
    - Changes take effect after logging off/on or restarting the system.

    Author: Generated by Cline
    Date: 10/17/2025
#>

#Requires -RunAsAdministrator

[CmdletBinding()]
param()

try {
    # Set OverlayTestMode to enable cursor fixes
    Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\Dwm" -Name "OverlayTestMode" -Value 5 -Type DWord

    Write-Host "Cursor fix applied successfully. Please log off/on or restart your computer for changes to take effect." -ForegroundColor Green
}
catch {
    Write-Error "Failed to apply cursor fix: $($_.Exception.Message)"
    exit 1
}
